name: Update gist with WakaTime stats
on:
  watch:
    types: started
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: dfc2722d3349f5cc707b721a3e964ab2
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
